#!/usr/bin/env ruby

demos = [
  "autumn",
  "colorful",
  "fruity",
  "monokai",
  "native",
  "perldoc",
  "trac",
  "vim"
]

demo_single_template = File.read('templates/demo-single.html')
demo_list_html = File.read('templates/demo-list.html')

demo_list = File.new("../index.html", "w")
demo_list_find = '<!-- DEMO_LIST -->'
demo_list_replace = ''

demos.each do |demo|
  out = File.new("../demos/#{demo}-converted.html", "w")
  out.puts "<link rel=\"stylesheet\" href=\"../#{demo}.css\">"
  out.puts demo_single_template
  out.close

  out = File.new("../demos/#{demo}-original.html", "w")
  out.puts "<link rel=\"stylesheet\" href=\"../original-stylesheets/#{demo}.css\">"
  out.puts demo_single_template
  out.close

  demo_list_replace += "<h3>#{demo}.css</h3>"
  demo_list_replace += "<iframe src=\"demos/#{demo}-converted.html\" title=\"#{demo}.css demo\"></iframe>"
end

demo_list_html.sub! demo_list_find, demo_list_replace
demo_list.puts demo_list_html
demo_list.close
